// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertActivity = `-- name: InsertActivity :exec
INSERT INTO task_activity (task_id, actor_id, action, changes)
VALUES ($1, $2, $3, $4)
`

type InsertActivityParams struct {
	TaskID  uuid.UUID   `json:"task_id"`
	ActorID pgtype.UUID `json:"actor_id"`
	Action  string      `json:"action"`
	Changes []byte      `json:"changes"`
}

func (q *Queries) InsertActivity(ctx context.Context, arg InsertActivityParams) error {
	_, err := q.db.Exec(ctx, insertActivity,
		arg.TaskID,
		arg.ActorID,
		arg.Action,
		arg.Changes,
	)
	return err
}

const listActivityForTask = `-- name: ListActivityForTask :many
SELECT a.id, a.action, a.changes, a.created_at, u.email AS actor_email
FROM task_activity a
LEFT JOIN users u ON u.id = a.actor_id
WHERE a.task_id = $1
ORDER BY a.created_at DESC, a.id DESC
LIMIT 50
`

type ListActivityForTaskRow struct {
	ID         int64     `json:"id"`
	Action     string    `json:"action"`
	Changes    []byte    `json:"changes"`
	CreatedAt  time.Time `json:"created_at"`
	ActorEmail *string   `json:"actor_email"`
}

func (q *Queries) ListActivityForTask(ctx context.Context, taskID uuid.UUID) ([]ListActivityForTaskRow, error) {
	rows, err := q.db.Query(ctx, listActivityForTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivityForTaskRow
	for rows.Next() {
		var i ListActivityForTaskRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.Changes,
			&i.CreatedAt,
			&i.ActorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
