// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteAttachment = `-- name: DeleteAttachment :execrows
DELETE FROM attachments
WHERE id = $1
`

func (q *Queries) DeleteAttachment(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAttachment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAttachmentWithOwner = `-- name: GetAttachmentWithOwner :one
SELECT a.id, a.task_id, a.filename, a.content_type, a.size_bytes, a.data, a.created_at,
       t.user_id AS owner_id
FROM attachments a
JOIN tasks t ON t.id = a.task_id
WHERE a.id = $1
`

type GetAttachmentWithOwnerRow struct {
	ID          uuid.UUID `json:"id"`
	TaskID      uuid.UUID `json:"task_id"`
	Filename    string    `json:"filename"`
	ContentType string    `json:"content_type"`
	SizeBytes   int32     `json:"size_bytes"`
	Data        []byte    `json:"data"`
	CreatedAt   time.Time `json:"created_at"`
	OwnerID     uuid.UUID `json:"owner_id"`
}

func (q *Queries) GetAttachmentWithOwner(ctx context.Context, id uuid.UUID) (GetAttachmentWithOwnerRow, error) {
	row := q.db.QueryRow(ctx, getAttachmentWithOwner, id)
	var i GetAttachmentWithOwnerRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Data,
		&i.CreatedAt,
		&i.OwnerID,
	)
	return i, err
}

const insertAttachment = `-- name: InsertAttachment :one
INSERT INTO attachments (task_id, filename, content_type, size_bytes, data)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, task_id, filename, content_type, size_bytes, created_at
`

type InsertAttachmentParams struct {
	TaskID      uuid.UUID `json:"task_id"`
	Filename    string    `json:"filename"`
	ContentType string    `json:"content_type"`
	SizeBytes   int32     `json:"size_bytes"`
	Data        []byte    `json:"data"`
}

type InsertAttachmentRow struct {
	ID          uuid.UUID `json:"id"`
	TaskID      uuid.UUID `json:"task_id"`
	Filename    string    `json:"filename"`
	ContentType string    `json:"content_type"`
	SizeBytes   int32     `json:"size_bytes"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) InsertAttachment(ctx context.Context, arg InsertAttachmentParams) (InsertAttachmentRow, error) {
	row := q.db.QueryRow(ctx, insertAttachment,
		arg.TaskID,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
		arg.Data,
	)
	var i InsertAttachmentRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const listAttachmentsForTask = `-- name: ListAttachmentsForTask :many
SELECT id, task_id, filename, content_type, size_bytes, created_at
FROM attachments
WHERE task_id = $1
ORDER BY created_at DESC
`

type ListAttachmentsForTaskRow struct {
	ID          uuid.UUID `json:"id"`
	TaskID      uuid.UUID `json:"task_id"`
	Filename    string    `json:"filename"`
	ContentType string    `json:"content_type"`
	SizeBytes   int32     `json:"size_bytes"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) ListAttachmentsForTask(ctx context.Context, taskID uuid.UUID) ([]ListAttachmentsForTaskRow, error) {
	rows, err := q.db.Query(ctx, listAttachmentsForTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAttachmentsForTaskRow
	for rows.Next() {
		var i ListAttachmentsForTaskRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
