// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (user_id, title, description, status, priority, due_date)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, title, description, status, priority, due_date, created_at, updated_at
`

type CreateTaskParams struct {
	UserID      uuid.UUID  `json:"user_id"`
	Title       string     `json:"title"`
	Description string     `json:"description"`
	Status      string     `json:"status"`
	Priority    string     `json:"priority"`
	DueDate     *time.Time `json:"due_date"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.DueDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTaskForUser = `-- name: DeleteTaskForUser :execrows
DELETE FROM tasks
WHERE id = $1 AND user_id = $2
`

type DeleteTaskForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteTaskForUser(ctx context.Context, arg DeleteTaskForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTaskForUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTaskForUser = `-- name: GetTaskForUser :one
SELECT id, user_id, title, description, status, priority, due_date, created_at, updated_at FROM tasks
WHERE id = $1 AND user_id = $2
`

type GetTaskForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetTaskForUser(ctx context.Context, arg GetTaskForUserParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskForUser, arg.ID, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskForUser = `-- name: UpdateTaskForUser :one
UPDATE tasks SET
    title       = COALESCE($1, title),
    description = COALESCE($2, description),
    status      = COALESCE($3, status),
    priority    = COALESCE($4, priority),
    due_date    = CASE WHEN $5::bool THEN $6 ELSE due_date END,
    updated_at  = now()
WHERE id = $7 AND user_id = $8
RETURNING id, user_id, title, description, status, priority, due_date, created_at, updated_at
`

type UpdateTaskForUserParams struct {
	Title       *string    `json:"title"`
	Description *string    `json:"description"`
	Status      *string    `json:"status"`
	Priority    *string    `json:"priority"`
	DueDateSet  bool       `json:"due_date_set"`
	DueDate     *time.Time `json:"due_date"`
	ID          uuid.UUID  `json:"id"`
	UserID      uuid.UUID  `json:"user_id"`
}

func (q *Queries) UpdateTaskForUser(ctx context.Context, arg UpdateTaskForUserParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskForUser,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.DueDateSet,
		arg.DueDate,
		arg.ID,
		arg.UserID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
